version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jira_db
      POSTGRES_USER: jira_user
      POSTGRES_PASSWORD: sua_senha_segura
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8006
    volumes:
      - .:/app
    ports:
      - "8006:8006"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=jira_db
      - POSTGRES_USER=jira_user
      - POSTGRES_PASSWORD=sua_senha_segura
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  pgdata:
