# Generated by Django 5.2.5 on 2025-09-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('SERVER', 'Server'), ('MAUI', 'Maui')], max_length=10)),
                ('first_release', models.CharField(max_length=10)),
                ('applied_releases', models.JSONField(default=list)),
                ('creation_date', models.DateField()),
                ('solution_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('informed_date', models.DateField()),
                ('jira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jira_project.jira')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='jira_project.customer')),
            ],
        ),
        migrations.AddField(
            model_name='jira',
            name='tickets',
            field=models.ManyToManyField(related_name='jiras', to='jira_project.ticket'),
        ),
    ]
